### ISSUE TITLE
Day counter stuck

### ISSUE THREAD

**Issue by AudunKodehode** [VilloKodeHode/Job-simulator#1]
Day counter is stuck at 
Day: 1
Week: 1
Month: 1

when game progressses.

**Comment by VilloKodeHode** [comment]
Denne fungerte da jeg laget den, men det er ikke vedlikeholdt, så ettersom kodespråket utvikler seg må endringer gjøres for at funksjonaliteten skal opprettholdes.

**Comment by VilloKodeHode** [comment]
Feilen var på linje 402 i job simulator.js filen: "=" -> "==="
